projects:
  mediavault:
    schemaPath: amplify/backend/api/mediavault/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
