name: run-pr-e2e
on:
  pull_request:
    types: [labeled]

jobs:
  run-pr-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: cloud-e2e
        run: |
          yarn cloud-e2e
